server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

  application:
    name: provider-payment8001

  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8

mybatis:
  ##config-location: classpath:mybatis/mybatis.cfg.xml                # mybatis配置文件所在路径
  mapper-locations: classpath*:com/xp/cloud/**/**/*.xml            # mapper映射文件

#eureka:
#  client:
#    register-with-eureka: true #表示向注册中心注册自己 默认为true
#    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
#    service-url:
#      defaultZone: http://localhost:7001/eureka/ # 入驻地址

##nacos 配置
  cloud:
   nacos:
    discovery:
     server-addr: localhost:8848


